// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.gov.nsw.records.digitalarchive.repo.model;

import au.gov.nsw.records.digitalarchive.repo.model.Repository;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Repository_Roo_Configurable {
    
    declare @type: Repository: @Configurable;
    
}
